### ISSUE TITLE
Set up your Kanban board

### ISSUE THREAD

**Issue by CRClothier** [CRClothier/JavaScript-Capstone#21]
Here is the repository link to our Kanban board:
https://github.com/CRClothier/JavaScript-Capstone/projects

In our team, we are 2 people.

**Comment by Amrhub** [comment]
# Approved 💯 ✅ 🥳 🎈 🎉 

Hi team, 👋🏻 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![](https://media.giphy.com/media/xT0xezQGU5xCDJuCPe/giphy.gif)


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
